//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACKCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_ARTICULO
    {
        public CMS_ARTICULO()
        {
            this.CMS_MENU = new HashSet<CMS_MENU>();
            this.CMS_ARCHIVO = new HashSet<CMS_ARCHIVO>();
            this.CMS_CATEGORIA = new HashSet<CMS_CATEGORIA>();
            this.CMS_IMAGEN = new HashSet<CMS_IMAGEN>();
        }
    
        public int ID_ARTICULO { get; set; }
        public System.DateTime UI_FECHA_ALTA { get; set; }
        public Nullable<System.DateTime> UI_FECHA_MODIFICACION { get; set; }
        public Nullable<System.DateTime> UI_FECHA_BAJA { get; set; }
        public string UI_USUARIO { get; set; }
        public string UI_INFO { get; set; }
        public int ID_TIPOARTICULO { get; set; }
        public int ID_ESTADOARTICULO { get; set; }
        public string TITULO { get; set; }
        public string ENCABEZADO { get; set; }
        public string CONTENIDO { get; set; }
        public string PATH_CONTENIDOEXT { get; set; }
        public string PATH_PLANCONTENIDOEXT { get; set; }
        public string PATH_CONTENIDOTRANS { get; set; }
        public string RESUMEN { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public string ACTIVO { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string OBSERVACIONES { get; set; }
        public string URLIMAGEN { get; set; }
    
        public virtual ICollection<CMS_MENU> CMS_MENU { get; set; }
        public virtual ICollection<CMS_ARCHIVO> CMS_ARCHIVO { get; set; }
        public virtual ICollection<CMS_CATEGORIA> CMS_CATEGORIA { get; set; }
        public virtual ICollection<CMS_IMAGEN> CMS_IMAGEN { get; set; }
    }
}
