//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_IMAGEN
    {
        public int ID { get; set; }
        public byte[] BinaryArr { get; set; }
        public int CMS_ARTICULO_ID { get; set; }
        public string Nombre { get; set; }
    
        public virtual CMS_ARTICULO CMS_ARTICULO { get; set; }
    }
}
