//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_TIPOARCHIVO
    {
        public CMS_TIPOARCHIVO()
        {
            this.CMS_ARCHIVO = new HashSet<CMS_ARCHIVO>();
        }
    
        public int ID_TIPO { get; set; }
        public string Nombre { get; set; }
        public string Extensiones { get; set; }
    
        public virtual ICollection<CMS_ARCHIVO> CMS_ARCHIVO { get; set; }
    }
}
