//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordIO
{
    using System;
    using System.Collections.Generic;
    
    internal partial class Work
    {
        public Work()
        {
            this.Author = new HashSet<Author>();
            this.Establishment = new HashSet<Establishment>();
            this.WorkDocument = new HashSet<WorkDocument>();
            this.MesasDePonenciasLibres = new HashSet<MesasDePonenciasLibres>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string FullWorkBody { get; set; }
        public int AreaID { get; set; }
        public int AckID { get; set; }
        public string NotasAdicionales { get; set; }
        public int EstadoID { get; set; }
        public string ComentariosDelEvaluador { get; set; }
        public Nullable<int> Puntaje { get; set; }
        public Nullable<int> PosicionEnElArea { get; set; }
        public string SupervisorUserId { get; set; }
        public Nullable<bool> Supervisado { get; set; }
        public string Autores { get; set; }
        public string Instituciones { get; set; }
        public Nullable<bool> TrabajoAprobado { get; set; }
        public Nullable<bool> TrabajoCompletoPresentado { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<System.DateTime> FechaResumenPresentado { get; set; }
        public Nullable<System.DateTime> FechaTrabajoPresentado { get; set; }
        public string Coordinadores { get; set; }
    
        internal virtual Accreditation Accreditation { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<Author> Author { get; set; }
        public virtual ICollection<Establishment> Establishment { get; set; }
        public virtual ICollection<WorkDocument> WorkDocument { get; set; }
        public virtual ICollection<MesasDePonenciasLibres> MesasDePonenciasLibres { get; set; }
    }
}
