//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkDocument
    {
        public int id { get; set; }
        public int WorkID { get; set; }
        public byte[] DocumentFile { get; set; }
        public bool IsResumen { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaSubido { get; set; }
    
        internal virtual Work Work { get; set; }
    }
}
