//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACKCMS.Contenidos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionSitio
    {
        public int id { get; set; }
        public string TituloCongreso { get; set; }
        public byte[] LogoCongreso { get; set; }
        public byte[] ComprobanteAsistenciaHeader { get; set; }
        public byte[] ComprobanteAsistenciaFooter { get; set; }
        public byte[] ComprobanteOradorHeader { get; set; }
        public byte[] ComprobanteOradorFooter { get; set; }
        public string TituloCortoCongreso { get; set; }
        public string DiasDelCongreso { get; set; }
        public string Ciudad { get; set; }
    }
}
