//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACKCMS.Contenidos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitosanitariasEntities : DbContext
    {
        public FitosanitariasEntities()
            : base("name=FitosanitariasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accreditation> Accreditations { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Establishment> Establishments { get; set; }
        public virtual DbSet<Work> Works { get; set; }
        public virtual DbSet<WorkArea> WorkAreas { get; set; }
        public virtual DbSet<WorkStatu> WorkStatus { get; set; }
        public virtual DbSet<CMS_ARCHIVO> CMS_ARCHIVO { get; set; }
        public virtual DbSet<CMS_ARTICULO> CMS_ARTICULO { get; set; }
        public virtual DbSet<CMS_CATEGORIA> CMS_CATEGORIA { get; set; }
        public virtual DbSet<CMS_MENU> CMS_MENU { get; set; }
        public virtual DbSet<CMS_TIPOARCHIVO> CMS_TIPOARCHIVO { get; set; }
    }
}
