//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcreditacionesBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Establecimiento { get; set; }
        public int IdWork { get; set; }
        public int IdEstablishment { get; set; }
        public Nullable<bool> IsPresenter { get; set; }
        public int OrderPosition { get; set; }
    
        public virtual Work Work { get; set; }
        public virtual Establishment Establishment { get; set; }
    }
}
