//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcreditacionesBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public Work()
        {
            this.Authors = new HashSet<Author>();
            this.Establishments = new HashSet<Establishment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public int AreaID { get; set; }
        public int AckID { get; set; }
        public string NotasAdicionales { get; set; }
        public int EstadoID { get; set; }
        public string ComentariosDelEvaluador { get; set; }
        public Nullable<int> Puntaje { get; set; }
        public Nullable<int> PosicionEnElArea { get; set; }
        public string SupervisorUserId { get; set; }
        public Nullable<bool> Supervisado { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Author> Authors { get; set; }
        public virtual ICollection<Establishment> Establishments { get; set; }
        public virtual Accreditation Accreditation { get; set; }
    }
}
